package net.codejava;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface ProductMapper {

    @Select("select count(*) from product WHERE CONCAT(id, ' ', name, ' ' , brand, ' ' , madein, ' ' , price) LIKE CONCAT('%',#{keyword},'%')  ")
    int listAllSortPageContainingCount(@Param("keyword") String keyword);

    @Select("select * from product WHERE CONCAT(id, ' ', name, ' ' , brand, ' ' , madein, ' ' , price) LIKE CONCAT('%',#{keyword},'%')  order by ${sortField}  ${sortDir} LIMIT ${pageSize} OFFSET ${pageOffset}")
    List<Product> listAllSortPageContaining(@Param("keyword") String keyword, @Param("sortField") String sortField, @Param("sortDir") String sortDir, @Param("pageSize") Integer pageSize, @Param("pageOffset") Long pageOffset);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table product
     *
     * @mbg.generated Mon Oct 31 06:50:01 CST 2022
     */
    @Delete({
        "delete from product",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table product
     *
     * @mbg.generated Mon Oct 31 06:50:01 CST 2022
     */
    @Insert({
        "insert into product (name, brand, ",
        "madein, price)",
        "values (#{name,jdbcType=VARCHAR}, #{brand,jdbcType=VARCHAR}, ",
        "#{madein,jdbcType=VARCHAR}, #{price,jdbcType=REAL})"
    })
    @SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Integer.class)
    int insert(Product row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table product
     *
     * @mbg.generated Mon Oct 31 06:50:01 CST 2022
     */
    @Select({
        "select",
        "id, name, brand, madein, price",
        "from product",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
        @Result(column = "name", property = "name", jdbcType = JdbcType.VARCHAR),
        @Result(column = "brand", property = "brand", jdbcType = JdbcType.VARCHAR),
        @Result(column = "madein", property = "madein", jdbcType = JdbcType.VARCHAR),
        @Result(column = "price", property = "price", jdbcType = JdbcType.REAL)
    })
    Product selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table product
     *
     * @mbg.generated Mon Oct 31 06:50:01 CST 2022
     */
    @Select({
        "select",
        "id, name, brand, madein, price",
        "from product"
    })
    @Results({
        @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
        @Result(column = "name", property = "name", jdbcType = JdbcType.VARCHAR),
        @Result(column = "brand", property = "brand", jdbcType = JdbcType.VARCHAR),
        @Result(column = "madein", property = "madein", jdbcType = JdbcType.VARCHAR),
        @Result(column = "price", property = "price", jdbcType = JdbcType.REAL)
    })
    List<Product> selectAll();

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table product
     *
     * @mbg.generated Mon Oct 31 06:50:01 CST 2022
     */
    @Update({
        "update product",
        "set name = #{name,jdbcType=VARCHAR},",
        "brand = #{brand,jdbcType=VARCHAR},",
        "madein = #{madein,jdbcType=VARCHAR},",
        "price = #{price,jdbcType=REAL}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Product row);
}
